apiVersion: v2
name: eck-apm-server
description: A Helm chart to deploy APM Server managed by the ECK Operator.
kubeVersion: ">= 1.21.0-0"
type: application
version: 0.1.0
sources:
  - https://github.com/elastic/cloud-on-k8s
  - https://github.com/elastic/apm-server
icon: https://helm.elastic.co/icons/apm-server.png
